#!/bin/bash

echo "compiling... sources"

(cd depends/JSAT; mvn compile)
(cd depends/ABAGAIL; ant all);

echo "Done."

echo "compiling project..."

javac -cp src/:depends/ABAGAIL/bin:depends/JSAT/target/classes:stdlib.jar -d bin src/Example.java

echo "done."
echo ""
echo ""
echo "running..."

java -cp bin/:depends/ABAGAIL/bin:depends/JSAT/target/classes:stdlib.jar Example

echo ""
echo ""
echo "done."
echo ""
echo ""

#(cd src; rm *.class)
#(cd depends/JSAT; mvn clean)
#(cd depends/ABAGAIL; ant clean);
