#!/bin/bash

clear

echo "compiling... sources"

(cd JSAT; mvn compile)

echo "Done."

echo "compiling project..."

javac -cp ABAGAIL/bin:.:JSAT/target/classes:stdlib.jar Example.java

echo "done."
echo ""
echo ""
echo "running..."

java -cp ABAGAIL/bin:.:JSAT/target/classes:stdlib.jar Example

echo ""
echo ""
echo "done."
echo ""
echo ""

echo "cleaning up..."

rm *.class
(cd JSAT; mvn clean)

echo "done."
